### ISSUE TITLE
README Installation instructions 

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [rpodcast/shinystate#3]
The `README` states that the package can be installed from `remotes::install_github("EliLillyCo/shinystate)`, but should this instead be `remotes::install_github("rpodcast/shinystate")` ?

**Comment by rpodcast** [comment]
Whoops! Thanks for catching that @mthomas-ketchbrook :smiley:

**Comment by mthomas-ketchbrook** [comment]
Still missing a trailing `"` 😉

**Comment by rpodcast** [comment]
I was a bit too trigger-happy on that last commit!
